---
# there is a problem:
# "Failed to preset unit: Transport endpoint is not connected"
# it seams that the source is the installation of:
# - acpid and
# - acpi-support
- name: masking package acpi* to install kubuntu-dasktop
  ansible.builtin.copy:
    src: kubuntu-desktop
    dest: /etc/apt/preferences.d/kubuntu-desktop
    owner: root
    group: root
    mode: '0644'